num1 = int(input("ตัวเลข 1 : "))
num2 = int(input("ตัวเลข 2 : "))
print(num1, "+", num2, "=", num1+num2)
print(num1, "+", num2, "=", num1-num2)
print(num1, "+", num2, "=", num1*num2)
print(num1, "+", num2, "=", num1/num2)
